version: '3'
services:
  mongo:
    image: mongo:4.4
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "3005:3005"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
